"""empty message

Revision ID: 3595c027c8e2
Revises: 
Create Date: 2022-04-13 15:39:25.099566

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3595c027c8e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('amps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('Combo', 'Head', 'Cabinet', 'Power Amp', 'Pre-Amp', name='type'), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('wattage', sa.Integer(), nullable=True),
    sa.Column('speaker_size', sa.Integer(), nullable=True),
    sa.Column('speaker_amount', sa.Integer(), nullable=True),
    sa.Column('power_type', sa.Enum('Tube', 'Solid State', 'Hybrid', name='power_type'), nullable=True),
    sa.Column('ohm_rating', sa.Enum('4', '8', '16', 'Multi', name='ohm_rating'), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('on_loan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guitars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('on_loan', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('make', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('color', sa.String(length=100), nullable=True),
    sa.Column('year', sa.String(length=4), nullable=True),
    sa.Column('is_working', sa.Boolean(), nullable=False),
    sa.Column('on_loan', sa.Boolean(), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rigs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('associations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rig_id', sa.Integer(), nullable=True),
    sa.Column('guitar_id', sa.Integer(), nullable=True),
    sa.Column('amp_id', sa.Integer(), nullable=True),
    sa.Column('pedal_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['amp_id'], ['amps.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['guitar_id'], ['guitars.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['pedal_id'], ['pedals.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['rig_id'], ['rigs.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('associations')
    op.drop_table('rigs')
    op.drop_table('pedals')
    op.drop_table('guitars')
    op.drop_table('amps')
    op.drop_table('profiles')
    op.drop_table('users')
    # ### end Alembic commands ###
